# Generated by Django 5.2.7 on 2025-10-22 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analyzed_strings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_palindrome'], name='analyzed_st_is_pali_4e89db_idx'), models.Index(fields=['word_count'], name='analyzed_st_word_co_bf6cd4_idx'), models.Index(fields=['length'], name='analyzed_st_length_6b6fd7_idx')],
            },
        ),
    ]
