# Generated by Django 5.2.7 on 2025-10-28 00:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_countries', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_status',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('population', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'countries',
                'indexes': [models.Index(fields=['name'], name='countries_name_19480f_idx'), models.Index(fields=['region'], name='countries_region_b10b30_idx'), models.Index(fields=['currency_code'], name='countries_currenc_41a129_idx'), models.Index(fields=['estimated_gdp'], name='countries_estimat_d064de_idx')],
            },
        ),
    ]
