# Generated by Django 5.2.7 on 2025-10-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemstatus',
            old_name='last_updated',
            new_name='last_refreshed_at',
        ),
    ]
